# Generated by Django 4.0.4 on 2022-10-17 15:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('type', models.CharField(choices=[('WA', 'Water'), ('GR', 'Grass'), ('GH', 'Ghost'), ('ST', 'Steel'), ('FA', 'Fairy')], max_length=30)),
                ('hp', models.PositiveBigIntegerField(validators=[django.core.validators.MaxLengthValidator(350), django.core.validators.MinLengthValidator(50)])),
                ('active', models.BooleanField(default=True)),
                ('name_fr', models.CharField(default='', max_length=30)),
                ('name_ar', models.CharField(default='', max_length=30)),
                ('name_jp', models.CharField(default='', max_length=30)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
